#!/bin/bash

# This script uploads CVs to the server

make html
scp tereza_dolezalova_casual_en.html jpapouse@zimodej.cz:/var/www/zimodej.cz/subdomeny/dodo/index.html
scp jan_papousek_en.html jpapouse@zimodej.cz:/var/www/zimodej.cz/subdomeny/papi/index.html
ssh jpapouse@zimodej.cz -t "rm -rf /var/www/zimodej.cz/subdomeny/papi/download; mkdir /var/www/zimodej.cz/subdomeny/papi/download"
scp .htaccess jpapouse@zimodej.cz:/var/www/zimodej.cz/subdomeny/papi/download
scp jan_papousek*.pdf jpapouse@zimodej.cz:/var/www/zimodej.cz/subdomeny/papi/download
ssh jpapouse@zimodej.cz -t "rm -rf /var/www/zimodej.cz/subdomeny/dodo/download; mkdir /var/www/zimodej.cz/subdomeny/dodo/download"
scp .htaccess jpapouse@zimodej.cz:/var/www/zimodej.cz/subdomeny/dodo/download
scp tereza_dolezalova*.pdf jpapouse@zimodej.cz:/var/www/zimodej.cz/subdomeny/dodo/download

